package com.example.administrator.myapplication.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table USER.
 */
public class User {

    private String uid;
    private String uname;
    private String nickname;
    private String mobile;
    private String gender;
    private String location;
    private String avatar;
    private String china_coin;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public User() {
    }

    public User(String uid) {
        this.uid = uid;
    }

    public User(String uid, String uname, String nickname, String mobile, String gender, String location, String avatar, String china_coin) {
        this.uid = uid;
        this.uname = uname;
        this.nickname = nickname;
        this.mobile = mobile;
        this.gender = gender;
        this.location = location;
        this.avatar = avatar;
        this.china_coin = china_coin;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getUname() {
        return uname;
    }

    public void setUname(String uname) {
        this.uname = uname;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getChina_coin() {
        return china_coin;
    }

    public void setChina_coin(String china_coin) {
        this.china_coin = china_coin;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
